# -*- coding: utf-8 -*-
"""
统一配置模块
"""
from .config import (
    BaseConfig,
    FundConfig,
    ChartConfig,
    PlotConfig,
    OcrConfig,
    ServerConfig,
    ConfigLoader,
    get_fund_config,
    get_chart_config,
    get_plot_config,
    get_server_config,
    get_ocr_config,
    get_legacy_config,
    validate_config,
    fund_config,
    chart_config,
    plot_config,
    server_config,
    ocr_config,
    CONFIG,
)

__all__ = [
    'BaseConfig',
    'FundConfig',
    'ChartConfig',
    'PlotConfig',
    'OcrConfig',
    'ServerConfig',
    'ConfigLoader',
    'get_fund_config',
    'get_chart_config',
    'get_plot_config',
    'get_server_config',
    'get_ocr_config',
    'get_legacy_config',
    'validate_config',
    'fund_config',
    'chart_config',
    'plot_config',
    'server_config',
    'ocr_config',
    'CONFIG',
]